# Generated by Django 3.1.7 on 2021-04-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0002_auto_20210422_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
